ALTER TABLE `proyecto`.`tabla_txt` 
CHANGE COLUMN `index_txt` `index_txt` INT(11) NOT NULL AUTO_INCREMENT ;




#Tras varios errores, nos hemos dado cuenta de que las longitudes originales establecidas para los VARCHAR eran insuficientes, por lo que
hemos decidido ampliar las longitudes de todas ellas para asegurar su correcta inserción

ALTER TABLE `proyecto`.`tabla_txt` 
CHANGE COLUMN `q3` `q3` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q4` `q4` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q5` `q5` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q6` `q6` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q7` `q7` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q8` `q8` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q9` `q9` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q11` `q11` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q12` `q12` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q13` `q13` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q14` `q14` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q15` `q15` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q16` `q16` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q17` `q17` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q20` `q20` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q21` `q21` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q22` `q22` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q23` `q23` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q24` `q24` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q25` `q25` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q26` `q26` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q32` `q32` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q33` `q33` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q34` `q34` VARCHAR(500) NULL DEFAULT NULL ,
CHANGE COLUMN `q35` `q35` VARCHAR(500) NULL DEFAULT NULL ;
